version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres:/var/lib/postgresql/data
  app:
    build:
      context: ./
    depends_on:
      - db
    ports:
      - 80:5000
    environment:
      DATABASE_URL: postgres://user:password@db/fastladder
      PORT: 5000
      SECRET_KEY_BASE: secret key base # ruby -r securerandom -e 'puts SecureRandom.hex(64)'
    command: foreman start
